### ISSUE TITLE
java.lang.NoSuchMethodError: No static method aspectOf()

### ISSUE THREAD

**Issue by xianjun-liu** [sensorsdata/sa-sdk-android-plugin#2]
```
Tinker.UncaughtHandler: catch exception when loading tinker:java.lang.NoSuchMethodError:
 No static method aspectOf()Lcom/sensorsdata/analytics/android/sdk/aop/RadioGroupOnCheckedChangeAspectj; in class Lcom/sensorsdata/analytics/android/sdk/aop/RadioGroupOnCheckedChangeAspectj; or its super classes (declaration of 'com.sensorsdata.analytics.android.sdk.aop.RadioGroupOnCheckedChangeAspectj' appears in /data/app/com.tianxi66.zxgb-1/base.apk)
                                                                               at com.dx168.zxgb.fragment.SelectStockFragment$1.onCheckedChanged(SelectStockFragment.java:135)
                                                                               at android.widget.RadioGroup.setCheckedId(RadioGroup.java:173)
                                                                               at android.widget.RadioGroup.access$600(RadioGroup.java:53)
                                                                               at android.widget.RadioGroup$CheckedStateTracker.onCheckedChanged(RadioGroup.java:351)
                                                                               at android.widget.CompoundButton.setChecked(CompoundButton.java:159)
                                                                               at android.widget.CompoundButton.toggle(CompoundButton.java:115)
                                                                               at android.widget.RadioButton.toggle(RadioButton.java:76)
                                                                               at android.widget.CompoundButton.performClick(CompoundButton.java:120)
                                                                               at android.view.View$PerformClick.run(View.java:21177)
                                                                               at android.os.Handler.handleCallback(Handler.java:742)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5527)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
                                                                           
```

**Comment by wangzhzh** [comment]
文档中的第四步加了吗？

第四步： 在 project 级别的 gradle.properties 中添加如下配置：
android.enableBuildCache=false

**Comment by xianjun-liu** [comment]
加了，现在可以了，谢谢！
